// words.js — loads the word corpus. Generated by Tools/build-words.mjs from
// Ordkrig's words.no.json; never hand-edit words.json (see CLAUDE.md Provenance).
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));

export function loadWords() {
  return JSON.parse(readFileSync(path.join(here, "words.json"), "utf8"));
}

export function loadFakeDefs() {
  return JSON.parse(readFileSync(path.join(here, "fakeDefs.json"), "utf8"));
}

export function wordById(words, id) {
  return words.find((w) => w.id === id);
}
