// words.js — loads the word corpus, one file pair per language (see
// js/config.js LANGS). words.no.json/fakeDefs.no.json are generated by
// Tools/build-words.mjs from Ordkrig's real corpus; never hand-edit them
// (see CLAUDE.md Provenance). words.en.json/fakeDefs.en.json are a
// hand-written PLACEHOLDER corpus, not generated by any script — see their
// own header comments and CLAUDE.md's "Dual-language gameplay" section.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));

export function loadWords(lang) {
  return JSON.parse(readFileSync(path.join(here, `words.${lang}.json`), "utf8"));
}

export function loadFakeDefs(lang) {
  return JSON.parse(readFileSync(path.join(here, `fakeDefs.${lang}.json`), "utf8"));
}

export function wordById(words, id) {
  return words.find((w) => w.id === id);
}
